### ISSUE TITLE
feat: More flexible choice of icons in components

### ISSUE THREAD

**Issue by Ushie** [KTibow/m3-svelte#101]
IconifyIcons includes so many icons from many icon packs, so it certainly was a smart decision choosing to be the provider of icons for the components

But, sometimes we need the icons to represent specific things, like entities, in that case, we'd want to use an HTMLImage

**Comment by KTibow** [comment]
- Not sure where this would be useful. The only component where the M3 specs include images AFAIK are lists, and those use slots now.
- You can already pass images as icons because SVGs can represent anything, including images.

**Comment by Ushie** [comment]
How would I pass an SVG to the icon parameter of components? The parameters expect an IconifyIcon, which is a format that is a bit different to SVGs

```ts
import type { IconifyIcon } from "@iconify/types";
const data: IconifyIcon = {
    width: 24,
    height: 24,
    body: "",
};
export default data;
```

**Comment by KTibow** [comment]
The IconifyIcon just gets turned into an SVG like `<svg width=${width} height=${height}>${body}</svg>`. You should be able to just take the body out of any SVG and use it.
