### ISSUE TITLE
TextFieldOutlined's label don't have the right background color

### ISSUE THREAD

**Issue by Axteli** [KTibow/m3-svelte#121]
When using `TextFieldOutlined`, the label use by default `background-color: rgb(var(--m3-util-background, var(--m3-scheme-surface)));` which should be customizable to avoid situations like the image below, where the background-color of the label doesn't match.

![image](https://github.com/user-attachments/assets/1de04f60-079c-42d0-8001-1528e76ea8ad)

**Comment by KTibow** [comment]
Guess what? `m3-util-background` is the customizable variable. Use it like this:
```svelte
<TextFieldOutlined --m3-util-background="var(--m3-scheme-surface-container)" />
```

Maybe I should put that in a comment because I think you're the 3rd person who's asked.
