### ISSUE TITLE
HEX codes near colors in scheme

### ISSUE THREAD

**Issue by pdimu** [KTibow/m3-svelte#122]
Adding a hex code near the generated scheme would be interesting and easier to use (aka no color pickers needed)

**Comment by KTibow** [comment]
You mean if you want to grab one of the generated colors?

**Comment by pdimu** [comment]
> You mean if you want to grab one of the generated colors? 

Yes

**Comment by KTibow** [comment]
Went ahead and [implemented my take on the feature](https://github.com/KTibow/m3-svelte/commit/8dabc00d56284e3c0bdd4338e97792f726f2cb55). I'll find it useful too. I tried to make it clean, and I hope that doesn't make it harder to use.

**Comment by pdimu** [comment]
@KTibow could you add a copy gliph or icon when you're hovering over the image?

**Comment by KTibow** [comment]
Done
