### ISSUE TITLE
Support for href property in Button component (renders as a link)

### ISSUE THREAD

**Issue by luis11011** [KTibow/m3-svelte#126]
It would be very useful to have native support for an `href` property in the `Button` component so that it can render as an anchor (`<a>`) element when required. This would allow developers to easily create buttons that link to external pages or sections of the app without needing to use a separate `<a>` tag alongside a button style.

### Expected Behavior:
- When an `href` property is provided to the `Button` component, it renders as an anchor (`<a>`) element instead of a `<button>`.
- The button retains all styling and Material 3 characteristics, but functions like a link.
  
### Use Case:
- Navigation links styled as buttons in a Material 3 design framework.
  
### Current Workaround:
- Manually wrapping the `<a>` element with custom styles or using a separate CSS class, which requires extra setup and reduces consistency with the built-in `Button` component.

### Proposed Solution:
- Modify the `Button` component to conditionally render an `<a>` tag when `href` is present, while keeping all default button functionality when no `href` is supplied.

### Additional context:
- This feature would align with the Material 3 guidelines, where buttons can act as links in certain navigation contexts.

**Comment by KTibow** [comment]
Check out `ButtonLink`. If you need to dynamically swap, you can do that with `svelte:component`.
