### ISSUE TITLE
GG

### ISSUE THREAD

**Issue by xafn** [KTibow/m3-svelte#5]
Just found out someone else is also making an m3-svelte library after searching on npm. Good work! While mine is mostly non-functional, I still have some components that you haven't implement such as the Dialog or Snackbar at https://m3-svelte.vercel.app/ Though my code isn't close to being as polished or done as yours, let me know if you want me to open a PR for these.

**Comment by KTibow** [comment]
looks pretty cool! i'd be happy to accept a pr, let me know if you want me to explain any of the code structure

**Comment by KTibow** [comment]
you still interested in this?

**Comment by KTibow** [comment]
cc @xafn
