### ISSUE TITLE
stuff i want to add

### ISSUE THREAD

**Issue by KTibow** [KTibow/m3-svelte#6]
starting with aria-labels

**Comment by KTibow** [comment]
improve prop handling

**Comment by KTibow** [comment]
more animations https://m3.material.io/styles/motion/transitions/transition-patterns

**Comment by KTibow** [comment]
more components

**Comment by KTibow** [comment]
improve how colors are handled in theming

**Comment by KTibow** [comment]
better transitions
use inset
actually improve prop handling

**Comment by JL102** [comment]
Wanna add a roadmap and pin it to the list of issues? I'm interested in contributing but don't know which components you've got planned and/or which ones you're already working on. (pro tip if you didn't know, you can do checkboxes like this:

```
- [ ] foo bar
```
and I'm pretty sure that on github issues, clicking on the checkboxes will automatically edit the markdown to check/uncheck them

**Comment by KTibow** [comment]
some big refactorings are
- update transitions (im working on)
- specify additional props separately instead of using $$props (im working on) 
- use inset instead of specifying each one, and other code quality things

**Comment by hubertmalkowski** [comment]
Hey! I'm interested in adding new features to the library. Should I discuss my ideas within this issue or create a new one specifically for each feature proposal?

**Comment by KTibow** [comment]
Make separate issues

**Comment by DeepBhat** [comment]
Do you have any plans for adding `Time` picker and `DateTime` picker?

**Comment by KTibow** [comment]
There aren't Docked variants documented in the spec. What's your use case? Should I try to make a Docked version anyway?

**Comment by DeepBhat** [comment]
This is the [component](https://m3.material.io/components/time-pickers/overview) I am talking about. I think it would be a great addition, and I'm willing to contribute.

**Comment by DeepBhat** [comment]
@KTibow That's correct, I'm using it in a form that allows the user to set a reminder on a ticket so they can get a notification. The reminder will have both date and time sections. I wasn't able to find any component for choose time in this library so that's why I asked.

**Comment by KTibow** [comment]
Is the input `datetime-local`?

**Comment by KTibow** [comment]
@DeepBhat 

a. are the date and time sections going to be unified?
b. is the time optional?

**Comment by DeepBhat** [comment]
a. Yes, that's what I was tasked to do. Select a date, and then select the time. Datetime picker in android does the same thing
b. Selecting the time is mandatory.

**Comment by KTibow** [comment]
@DeepBhat 

Since M3 doesn't have a dedicated mixed picker, how would you feel about using something like the one from GTasks?
(It has a button to open the picker. The picker has a date chooser, and a item that says set time. The item opens the time picker when clicked.)

**Comment by DeepBhat** [comment]
Yes thas a great idea. Honestly just having a time picker would suffice for my use case. I can work on creating one that follows material 3 guidelines. I just wanted to know if you have it in your road map.

**Comment by KTibow** [comment]
Yeah you can go ahead and try to make a time picker, I'll see how it turns out
