### ISSUE TITLE
Less restrictive open source license

### ISSUE THREAD

**Issue by conr2d** [KTibow/m3-svelte#75]
Thank you for sharing your project. I like your works and want to test them in my personal or commercial products, but not all my works can be open sourced due to the contract.

Can you change or add (e.g. dual license) a less restrictive license like Apache-2.0 or MIT?

Even if you don't want it, I will fully respect your decision.

**Comment by KTibow** [comment]
@kwaa @JL102 can you agree to license your contributions under the apache license

**Comment by kwaa** [comment]
I'm fine with that.

**Comment by KTibow** [comment]
I think Apache should be available now.
