### ISSUE TITLE
LinkTabs don't switch

### ISSUE THREAD

**Issue by Suyashtnt** [KTibow/m3-svelte#77]
rt. Despite being on the amenities page the tabs don't show this
![image](https://github.com/KTibow/m3-svelte/assets/45307955/47b46afd-46a3-4862-b5c8-5be9b56d6a47)

**Comment by KTibow** [comment]
are you sure you passed an updated `tab`

**Comment by Suyashtnt** [comment]
> are you sure you passed an updated `tab`

Oh I'm stupid. I thought IT would sync the tabs automatically. I'll check in a few hours once on PC

**Comment by Suyashtnt** [comment]
Yep it works
