### ISSUE TITLE
Tab bar gets squished on mobile

### ISSUE THREAD

**Issue by Suyashtnt** [KTibow/m3-svelte#79]
rt

![image](https://github.com/KTibow/m3-svelte/assets/45307955/b40886c8-1009-4945-95d8-ee1474cbfe40)

permalink to bug: https://586689da.37ob.pages.dev

**Comment by KTibow** [comment]
Problem is that the tabs are the equal-width version, and there's no easy way to transform them into proportional width (especially given the way the tab indicator animates - I would need JS to make it animate properly with proportional tabs).

If you wouldn't mind could you
1. Consider if any other options would work as well or better (eg grouping your content together, using buttons instead, etc), and stop this flow if they do
2. Research how Google handles this situation by looking through some Material 3 apps on mobile, seeing what they do on tablet or desktop, and reading the Material 3 docs on tabs
3. Come to a conclusion on how this should be handled (should you make your own component? should I make a separate component? and if so, how should it function across widths?)

**Comment by Suyashtnt** [comment]
> Problem is that the tabs are the equal-width version, and there's no easy way to transform them into proportional width (especially given the way the tab indicator animates - I would need JS to make it animate properly with proportional tabs).
> 
> If you wouldn't mind could you
> 
> 1. Consider if any other options would work as well or better (eg grouping your content together, using buttons instead, etc), and stop this flow if they do
> 2. Research how Google handles this situation by looking through some Material 3 apps on mobile, seeing what they do on tablet or desktop, and reading the Material 3 docs on tabs
> 3. Come to a conclusion on how this should be handled (should you make your own component? should I make a separate component? and if so, how should it function across widths?)

1. I can't really think of any other way that doesn't break the flow of the page

2. https://m3.material.io/components/tabs/guidelines#b0e3794c-059f-41e2-87a6-fe2498fc7fe8 seems that google uses scrollable tabs. Also see https://m3.material.io/components/tabs/guidelines#2691a4ac-ea12-467e-8568-de0c024e89e6

3. I think make scrolling tabs its own component, since its treated as seperate under material 3

**Comment by KTibow** [comment]
Closed since VariableTabs were added
