### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ferivoq** [KTibow/m3-svelte#81]
There is no documentation as far as I see so I don't know how to import or anything like I don't know how to import in StyleFromScheme. import { StyleFromScheme } from '@m3-svelte';. This doesn't work for example. Can you make a documentation for all the componentes?

**Comment by KTibow** [comment]
While docs would be good, I have no interest in documenting everything. You can view the [components code](https://github.com/KTibow/m3-svelte/tree/main/src/lib) and [how they're used on the website](https://github.com/KTibow/m3-svelte/tree/main/src/routes) already.

**Comment by hubertmalkowski** [comment]
I would be more than happy to help with documentation.

**Comment by KTibow** [comment]
If you want to create a PR to upgrade the "use" page to use headers and have some more in-depth code examples go ahead. If you want to, tell me, but if you don't within a day I'll implement this myself.

**Comment by hubertmalkowski** [comment]
I can do this, but it would be done within 2-3 days.

**Comment by KTibow** [comment]
I wasn't really clear in my original message, I meant more "if you don't say you're planning to do this within a day i'll do it, if you do say you're planning to i'll wait", but on second thought I'm just going to implement this myself, thanks for reminding me about this though.

**Comment by hubertmalkowski** [comment]
No problem. Can you also add an option to copy the tailwind theme in docs?

Meanwhile I can work on some other part of documentation if you want to enhance any of it.

**Comment by KTibow** [comment]
@hubertmalkowski check out the new docs and tell me your thoughts

**Comment by hubertmalkowski** [comment]
It is cool. However, I would suggest placing all code snippets within collapsible blocks that allow users to copy them directly to their clipboards with a single click. Similar to the ones found at this link: https://svelte-materialify.vercel.app/getting-started/installation/#install-with-default-styles (in the M3 style, of course).

**Comment by KTibow** [comment]
I redesigned the docs once more, with an emphasis on getting components working as fast as possible. I don't quite love the design but it's good enough. Any thoughts on the contents of the docs now?

**Comment by PlkMarudny** [comment]
But there are no docs? What does it mean, for example:

```svelte
import { StyleFromScheme } from 'm3-svelte';
...
[your theme snippet]
```

**Comment by KTibow** [comment]
Slightly updated the wording to clarify.

**Comment by KTibow** [comment]
I'm going to close this tomorrow if I don't get a reply.
