### ISSUE TITLE
Allow passing custom classes

### ISSUE THREAD

**Issue by Frioo** [KTibow/m3-svelte#84]
First of all: Great work on the library, the components look amazing.

It'd be nice to have the ability to pass custom classes to components.
It only takes a simple modification for each component to allow this, here's an example on `Button.svelte`

```svelte
<button
  on:click|stopPropagation
  {disabled}
  class="m3-container m3-font-label-large {type} icon-{iconType} {$$props.class}" <--- this part
  style="display: {display};"
  {...extraOptions}
>
  <div class="layer" />
  <slot />
</button>
```

`$$props.class` will add all classes passed to the component, which makes it very easy to customise the positioning, sizing, etc.

I use the modified component like so (tailwind, in this case):
```svelte
<Button type="filled" class="absolute right-2">Load</Button>
```

**Comment by KTibow** [comment]
This breaks unused class detection plus you can already accomplish this via extraOptions

**Comment by KTibow** [comment]
Closing as there are other ways to accomplish this
- using extraOptions
- using `:global`
- using other methods of positioning elements like flex

See [RatRater2](https://github.com/KTibow/RatRater2) for an example of a project that uses Tailwind with m3-svelte
