### ISSUE TITLE
Button changes

### ISSUE THREAD

**Issue by hubertmalkowski** [KTibow/m3-svelte#93]
### 1. The `type` prop on Button
The `type` prop is the same name as one of the default html button attributes. I know I can access it through `extraOptions` but it is not too handy.  HtmlButtonAttributes type can be actually combined using `$$Props` helper. And I would rename `type` prop to variant. I know it is a breaking change so I don't want to push too hard on this.

Reference: https://svelte.dev/docs/basic-markup#attributes-and-props

### 2. Button and ButtonLink could be combined into one component. 
Reference: https://github.com/huntabyte/bits-ui/blob/main/src/lib/bits/button/components/button.svelte

**Comment by KTibow** [comment]
> The type prop is the same name as one of the default html button attributes. I know I can access it through extraOptions but it is not too handy. 

Have you been setting this on every button? 

> Button and ButtonLink could be combined into one component

Separating them allows for stricter type checking and often smaller bundles

**Comment by KTibow** [comment]
I'm going to close this tomorrow if I don't get a reply.
