### ISSUE TITLE
How well does this follow Material's accessibility standards?

### ISSUE THREAD

**Issue by pernydev** [KTibow/m3-svelte#98]
Hi! We are looking to use this in an application with a lot of visually impaired users, such as screen reader users. I'm just wondering, how well does this meet the accessibility specifications of M3? Thank you!

**Comment by pernydev** [comment]
Thank you for responding so quickly. It is totally understandable that accessibility was not a top priority. I'll forward the website to a member of our team who uses a screen reader to get some feedback.

**Comment by KTibow** [comment]
any updates?

to be clear: almost everything uses semantic elements that you can interact with. it's just that some stuff like icons doesn't have labels.

**Comment by pernydev** [comment]
My email was left in the drafts! Our team member checked it out and this is (translated) what they said: "The example elements on the page, at least most of them seem to work nicely with VoiceOver. So probably you could get a nicely accessible application made, but a little difficult to say since I can't test them out in practice."

**Comment by KTibow** [comment]
closing as this seems answered
